modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/OFA-Tech/RegistryCleanupTool-MinecraftMod/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/OFA-Tech/RegistryCleanupTool-MinecraftMod"
authors="OFA Tech"
description='''
Server-side NeoForge utility mod that helps clean orphaned registry blocks/entities from worlds after mod removal.
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
